// function suma (a, b) {

//     return (a + b)
// }

// console.log (suma (2, 3))

// let resultado = suma (2, 3)

// arrays

// let flavors = ['chocolate', 'pistacho', 'macadamia', 'oreo']

// console.log(flavors)

// function impri(item){
//     console.log(item)
// }
// flavors.forEach (console.log)

// function multipli (a,b){
//     return a*b
// }

// console.log (multipli(2,3))

// console.log (multipli(3,6))

//objetos

let user = {
    name: "carlos",
    age: 200,
    Direccion {
        cra: 69c
        calle: 32c
        numero: 76
    }
    sayhi: function ()
    console.log ('hi')
}

console.log(user.name)